### ISSUE TITLE
Repo rename: CMIP6_DataRequest_CF_issues -> CMIP6_DataRequest_Issues

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/CMIP6_DataRequest_CF_issues#2]
@martinjuckes it would seem that the `_CF_` in the repo name is a little too specific. I assume you want all CMIP6 Data Request issues to be added here? Or if not, should we point such issues to another repo?

@dnadeau4 @taylor13 pinging you here

**Comment by martinjuckes** [comment]
No ... this is for CF issues. Issues about variable definitions are in https://github.com/cmip6dr/variableDefinitions
